//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatCMS._system.tools {
    
    public partial class UpgradePage {
        protected System.Web.UI.HtmlControls.HtmlGenericControl updatecontent;
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.TextBox tb_TestConnectionString;
        protected System.Web.UI.WebControls.Button b_ValidateConfig;
        protected System.Web.UI.WebControls.PlaceHolder ph_ValidationErrors;
        protected System.Web.UI.WebControls.Button b_UpdateDatabase;
        protected System.Web.UI.WebControls.PlaceHolder ph_UpdateDatabaseMessage;
    }
}
